"""Closed-loop evolution: problem generators, rank compression, continued training from an inherited adapter, archive, full loop on a tiny model."""
from __future__ import annotations

import json

import pytest

from lerp.evolution import problems
from lerp.evolution.archive import Archive, Organism


# ----------------------------------------------------------------------------------------------- problems
def test_questions_have_exact_answers_and_splits_are_disjoint():
    for family in problems.FAMILIES:
        parts = problems.splits(family, 200, 50, 80, seed=3)
        sets = {k: {r["q"] for r in v} for k, v in parts.items()}
        assert [len(v) for v in parts.values()] == [200, 50, 80]
        assert not (sets["train"] & sets["dev"]) and not (sets["train"] & sets["test"]) and not (sets["dev"] & sets["test"])
        for row in parts["test"]:
            expression = row["q"].rstrip("= ").replace("Q: ", "")
            assert str(eval(expression, {"__builtins__": {}})) == row["a"]  # noqa: S307 - generated by us, digits and + - * only
    assert problems.splits("chain", 50, 10, 10, 3) == problems.splits("chain", 50, 10, 10, 3)
    assert problems.splits("chain", 50, 10, 10, 3) != problems.splits("chain", 50, 10, 10, 4)


def test_verify_checks_the_first_integer_of_the_completion():
    row = {"q": "2 + 2 =", "a": "1018"}
    assert problems.verify(row, " 1,018\n") and problems.verify(row, "1018 is the answer")
    assert not problems.verify(row, " 1019") and not problems.verify(row, "no number")
    assert problems.sft_pair({"q": "2 + 2 =", "a": "4"}) == ("Q: 2 + 2 =\nA:", " 4\n")


def test_unknown_family_and_exhausted_pool_are_rejected():
    with pytest.raises(ValueError, match="unknown"):
        problems.pool("nope", 3, 0)


def test_local_jsonl_task_is_hashed_into_the_protocol(tmp_path):
    from lerp.tasks import resolve_task
    path = tmp_path / "x.jsonl"
    digest = problems.write_jsonl(problems.pool("add", 5, 1), path)
    task = resolve_task("x", problems.task_definition(path))
    assert task.generative and task.data_sha256() == digest
    docs = task.documents(1, 3)
    assert len(docs) == 2 and docs[0][0].startswith("Q: ")


# ----------------------------------------------------------------------------------------------- archive
def test_archive_is_append_only_and_tracks_lineage_and_niches(tmp_path):
    arc = Archive(tmp_path)
    arc.record(Organism(id="a", generation=0, op="founder", adapter="adapters/a", dev={"add": .9, "mul": .1}))
    arc.record(Organism(id="b", generation=0, op="founder", adapter="adapters/b", dev={"add": .2, "mul": .8}))
    arc.record(Organism(id="c", generation=1, op="cross+learn", adapter="adapters/c", parents=["a", "b"], dev={"add": .5, "mul": .5}))
    arc.record(Organism(id="d", generation=2, op="cross+learn", adapter="adapters/d", parents=["c", "b"], dev={"add": .6, "mul": .6}))
    assert arc.lineage("d") == ["a", "b", "c", "d"]
    assert arc.niches(["a", "b", "c", "d"], ["add", "mul"]) == {"add": "a", "mul": "b"}
    arc.organisms["c"].status = "survivor"
    arc.record(arc.organisms["c"])
    reloaded = Archive(tmp_path)  # the log replays to the latest line per organism
    assert reloaded.organisms["c"].status == "survivor" and len(reloaded.log.read_text().splitlines()) == 5


# ---------------------------------------------------------------------------------- learning (tiny model)
torch = pytest.importorskip("torch")
pytest.importorskip("transformers")
pytest.importorskip("tokenizers")
pytest.importorskip("peft")

from transformers import AutoModelForCausalLM, LlamaConfig, PreTrainedTokenizerFast  # noqa: E402

from lerp.evolution.learning import LearningError, compress_adapter, train_adapter  # noqa: E402

CHARS = list(" \n0123456789+-*=:QA")


def _tiny_base(path):
    from tokenizers import Regex, Tokenizer, models, pre_tokenizers
    vocab = {c: i + 1 for i, c in enumerate(CHARS)}
    vocab["[UNK]"] = 0
    tok = Tokenizer(models.WordLevel(vocab, unk_token="[UNK]"))
    tok.pre_tokenizer = pre_tokenizers.Split(Regex("."), behavior="isolated")
    torch.manual_seed(0)
    cfg = LlamaConfig(vocab_size=len(vocab), hidden_size=32, intermediate_size=48, num_hidden_layers=2, num_attention_heads=4,
                      num_key_value_heads=4, max_position_embeddings=128, tie_word_embeddings=True)
    AutoModelForCausalLM.from_config(cfg).save_pretrained(path)
    PreTrainedTokenizerFast(tokenizer_object=tok, unk_token="[UNK]").save_pretrained(path)


def _pairs(n=40, family="add"):
    return [problems.sft_pair(r) for r in problems.pool(family, n, 1)]


def _delta(adapter_dir):
    from safetensors.torch import load_file
    cfg = json.loads((adapter_dir / "adapter_config.json").read_text())
    scale = cfg["lora_alpha"] / cfg["r"]
    tensors = load_file(str(adapter_dir / "adapter_model.safetensors"))
    return {k.replace(".lora_A.weight", ""): scale * tensors[k.replace("lora_A", "lora_B")].float() @ tensors[k].float()
            for k in tensors if ".lora_A." in k}


def test_training_reduces_loss_and_continuing_from_an_adapter_changes_it(tmp_path):
    base = tmp_path / "base"
    _tiny_base(base)
    first = train_adapter(str(base), _pairs(), tmp_path / "a", steps=30, lr=5e-3, rank=4, seed=1, dtype="float32", batch=4, accum=1, max_len=48)
    short = train_adapter(str(base), _pairs(), tmp_path / "a0", steps=2, lr=5e-3, rank=4, seed=1, dtype="float32", batch=4, accum=1, max_len=48)
    assert first["final_loss"] < short["final_loss"] and first["pairs_sha256"] == short["pairs_sha256"]
    second = train_adapter(str(base), _pairs(40, "mul"), tmp_path / "b", init=tmp_path / "a", steps=10, lr=5e-3, seed=2, dtype="float32",
                           batch=4, accum=1, max_len=48)
    assert second["init"] == str(tmp_path / "a")
    before, after = _delta(tmp_path / "a"), _delta(tmp_path / "b")
    assert before.keys() == after.keys() and any(not torch.allclose(before[k], after[k]) for k in before)  # inherited, then changed
    with pytest.raises(LearningError):
        train_adapter(str(base), [], tmp_path / "c", steps=1)
    with pytest.raises(LearningError, match="longer"):
        train_adapter(str(base), _pairs(4), tmp_path / "d", steps=1, max_len=3, dtype="float32")


def test_compress_adapter_is_exact_when_the_rank_suffices_and_best_otherwise(tmp_path):
    from safetensors.torch import save_file
    torch.manual_seed(1)
    out_dim, in_dim, r = 12, 10, 6
    A, B = torch.randn(r, in_dim), torch.randn(out_dim, r)
    src = tmp_path / "src"
    src.mkdir()
    name = "base_model.model.model.layers.0.self_attn.q_proj"
    save_file({f"{name}.lora_A.weight": A, f"{name}.lora_B.weight": B}, str(src / "adapter_model.safetensors"))
    (src / "adapter_config.json").write_text(json.dumps({"r": r, "lora_alpha": 2 * r, "target_modules": ["q_proj"]}))
    full = 2.0 * B @ A
    info = compress_adapter(src, tmp_path / "full", r)
    assert info["rank_out"] == r and info["energy_kept"] == pytest.approx(1.0)
    assert torch.allclose(_delta(tmp_path / "full")[name], full, atol=1e-4)
    small = compress_adapter(src, tmp_path / "small", 2)
    approx = _delta(tmp_path / "small")[name]
    U, S, Vh = torch.linalg.svd(full)
    best = (U[:, :2] * S[:2]) @ Vh[:2]
    assert torch.allclose(approx, best, atol=1e-4)  # Eckart-Young: the truncated SVD is the best rank-2 approximation
    assert small["rank_out"] == 2 and 0 < small["energy_kept"] < 1
    assert json.loads((tmp_path / "small" / "adapter_config.json").read_text())["lora_alpha"] == 2  # scale 1 after compression


# ------------------------------------------------------------------------------------------ full loop
def test_the_loop_runs_end_to_end_and_records_lineage_and_a_verdict(tmp_path):
    from lerp.evolution.orchestrator import EvolutionConfig, run_evolution
    base = tmp_path / "base"
    _tiny_base(base)
    cfg = EvolutionConfig(base_model=str(base), device="cpu", dtype="float32", n_train=60, n_dev=8, n_test=16, founder_steps=4, child_steps=3,
                          generations=2, children=2, survivors=2, rank=4, lr=3e-3, batch=2, accum=1, seed=1, max_new_tokens=4)
    logs: list[str] = []
    result = run_evolution(cfg, tmp_path / "out", log=logs.append)
    arc = Archive(tmp_path / "out" / "archive")
    assert {"g0-add", "g0-mul"} <= set(arc.organisms)
    children = [o for o in arc.organisms.values() if o.op == "cross+learn"]
    assert len(children) == 4 and all(len(o.parents) == 2 and o.training["compression"]["rank_out"] == 4 for o in children)
    assert result["best"] in arc.organisms and arc.lineage(result["best"])[0].startswith("g0-")
    assert {"base", "merge-only", "control-plain"} <= set(result["test_accuracy"])
    assert result["training_steps"] == {"evolution": 4 * 3, "control": 4 * 3}  # the control gets exactly the evolution's training steps
    assert set(result["checks"]) == {"new_skill_learned", "old_skills_retained", "evolution_beats_plain_training"}
    assert isinstance(result["verdict"], str) and (tmp_path / "out" / "result.json").is_file()
    assert not (tmp_path / "out" / "tmp").exists()
    # test split: nothing the loop trained on appears in it
    test_questions = {r["q"] for fam in ("add", "mul", "chain")
                      for r in map(json.loads, (tmp_path / "out" / "data" / f"{fam}_eval.jsonl").read_text().splitlines())}
    train_questions = {r["q"] for fam in ("add", "mul", "chain")
                       for r in map(json.loads, (tmp_path / "out" / "data" / f"{fam}_train.jsonl").read_text().splitlines())}
    assert not (test_questions & train_questions)
